version: '3.8'

services:
  redis:
    container_name: redis
    image: redis:7.0.11
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/conf/redis.conf
    labels:
      - "name=redis"
      - "mode=standalone"
    restart: always
    command: redis-server /usr/local/conf/redis.conf

  # redis-cache:
  #   container_name: redis-cache-server
  #   image: redis:7.0.11
  #   ports:
  #     - 6380:6380
  #   volumes:
  #     - ./redis-cache-server/data:/data
  #     - ./redis-cache-server/conf/redis.conf:/usr/local/conf/redis.conf
  #   labels:
  #     - "name=redis"
  #     - "mode=standalone"
  #   restart: always
  #   command: redis-server /usr/local/conf/redis.conf
    